### ISSUE TITLE
Missing display.framebuffer_for_viewport Symbol

### ISSUE THREAD

**Issue by uxtechie** [flyaruu/rc-car-dashboard#1]
Hello,

The symbol `display.framebuffer_for_viewport` appears to be missing.

### Environment
- Project dependencies (Both repositories checked): 
* https://github.com/flyaruu/t-display-s3-amoled-rs
* https://github.com/bh1xuw/t-display-s3-amoled-rs

### Expected Behavior
I expected to find the `display.framebuffer_for_viewport` symbol available for use.

### Actual Behavior
The symbol `display.framebuffer_for_viewport` is not available, leading to compilation errors.

### Possible Solution
While I do not have a direct solution, I suspect that the symbol might have been deprecated or renamed in a recent update. Any guidance or workaround would be greatly appreciated.

Thank you for looking into this issue.

Best regards,

Julian

**Comment by flyaruu** [comment]
Hi Julian, ahh, no this is totally my bad, added that method, forgot to commit (also plan to upstream it to bh1xuw, but completely forgot. I've committed my change, so my fork _should_ work now, and hopefully the upstream will work soon.

**Comment by uxtechie** [comment]
Hi Flyaruu,

Thanks a bunch for the quick fix! Just gave it a go, and everything's compiling smoothly now. You nailed it with that update.

Cheers for sorting it out so fast. I'll keep an eye out for the upstream update too.

Best,
Julian

**Comment by flyaruu** [comment]
Excellent! Curious on what you're making!

**Comment by uxtechie** [comment]
Hey,

I'm actually just getting my feet wet with asynchronous programming in Rust, particularly using Embassy. Still at the learning stage, but it's pretty exciting!

Cheers,
Julian
